eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOST:http://localhost:8086/eureka/}
  instance:
    instance-id: karen-instance-${random.uuid}
spring:
  application:
    name: karen
server:
  port: 8080